export const soundfx = [
    {"name": "elevator waiting", "url":"elevator_2jN6tnc","color":"blue"},
    {"name": "epic meal time crow sound", "url":"epic-mealtime-crow-sound","color":""},
    {"name": "shooting stars", "url":"untitled-1_qPskhfn","color":""},
    {"name": "rick rolled", "url":"epic","color":""},
    {"name": "owen wowson 5", "url":"owenwowson5","color":""},
    {"name": "owen wowson 2", "url":"owenwowson2","color":""},
    {"name": "owen wowson 4", "url":"owenwowson4","color":""},
    {"name": "owen wowson 3", "url":"owenwowson3","color":""},
    {"name": "ding-sound-effect", "url":"ding-sound-effect_2","color":""},
    {"name": "mlg air horn", "url": "mlg-air-horn","color":""},
    {"name": "anime wow", "url": "anime-wow-sound-effect_Q6Q4ech","color":""},
    {"name": "oh yeah", "url": "oh-yeah","color":""},
    {"name": "bateria tum dum tss", "url": "bateria-tum-dum-tss","color":""},
    {"name": "chewbacca", "url": "chewbacca","color":""},
    {"name": "censor beep 1", "url": "censor-beep-1","color":""},
    {"name": "censor beep 2", "url": "censor-beep-2","color":""},
    {"name": "censor beep 3", "url": "censor-beep-3","color":""},
    {"name": "buzzer", "url": "wrong-answer-sound-effect","color":""},
    {"name": "minecraft hurt", "url": "minecraft-hurt","color":""},
    {"name": "sad trombone", "url": "sad-trombone","color":""},
    {"name": "whip", "url": "whip","color":""},
    {"name": "u cant touch this", "url": "mc-hammer-u-cant-touch-this","color":""},
    {"name": "hitmarkermp3", "url": "hitmarker_2","color":""},
    {"name": "error sound", "url": "error_CDOxCYm","color":""},
    {"name": "door knocking sound effect", "url": "crazy-realistic-knocking-sound-troll-twitch-streamers_small","color":""},
    {"name": "hello darkness my old frieend", "url": "saaaadaffleck","color":""},
    {"name": "finish him", "url": "finishhim","color":""},
    {"name": "mario jump", "url": "mario-jump","color":""},
    {"name": "clapping", "url": "clapping","color":""},
    {"name": "wrong", "url": "wrong","color":""},
    {"name": "mario 1 up", "url": "mario-1-up","color":""},
    {"name": "snoop dogg meme", "url": "tmpbxydyrz3"},

    {"name": "thug life (snoop)", "url": "snoop-dogg-base-instrumental-mp3cut","color":""},
    {"name": "ka ching", "url": "ka-ching","color":""},
    {"name": "spongebob a few moments later ", "url": "a-few-moments-later-hd","color":""},
    {"name": "doh", "url": "doh","color":""},
    {"name": "bongo feet", "url": "bongo-feet","color":""},
    {"name": "gayyyy", "url": "gayyy","color":""},
    {"name": "kids cheering", "url": "kids_cheering","color":""},
    {"name": "surprise motherfucka", "url": "surprise-motherfucka","color":""},
    {"name": "aint nobody got time", "url": "aint-nobody-got-time","color":""},
    {"name": "dun dun", "url": "dun-dun","color":""},
    {"name": "i like turtles", "url": "i-like-turtles","color":""},
    {"name": "mario jump", "url": "mario-jump","color":""},
    {"name": "epic sax button", "url": "epic-sax-guy-plays-for-57-minutes","color":""},
    {"name": "cuek", "url": "cuek"}, 
    {"name": "punch1", "url": "punch","color":""},
    {"name": "dolphin censor", "url": "spongebob-dolphin-censor","color":""},
    {"name": "bruh meme", "url": "movie_1_C2K5NH0","color":""},
    {"name": "jeopardy", "url": "jeopardy","color":""},
    {"name": "sonic ring", "url": "26f8b9_sonic_ring_sound_effect","color":""},
    {"name": "wilhelm scream", "url": "wilhelmscream","color":""},
    {"name": "sneaky snitch", "url": "sneaky-snitch","color":""},
    {"name": "eye of the tiger", "url": "eye-of-the-tiger","color":""},
    {"name": "please stand by", "url": "please-stand-by-video-effect","color":""},
    {"name": "sitcom audience laughing", "url": "sitcom-laughing","color":""},
    {"name": "ill be back", "url": "ill-be-back"}
];